import csv


OBSERVATIONS = {
    'observations': [
        {
            'id': 1,
            'label': 'Pace',
            'description': 'How would you rate the pacing of this book?',
            'multi_choice': True,
            'order': [4, 5, 6, 7],
            'values': [
                {'id': 1, 'name': 'Slow', 'deleted': True},
                {'id': 2, 'name': 'Medium', 'deleted': True},
                {'id': 3, 'name': 'Fast', 'deleted': True},
                {'id': 4, 'name': 'Slow paced'},
                {'id': 5, 'name': 'Medium paced'},
                {'id': 6, 'name': 'Fast paced'},
                {'id': 7, 'name': 'Meandering'},
            ],
        },
        {
            'id': 2,
            'label': 'Enjoyability',
            'description': 'How much did you enjoy reading this book?',
            'multi_choice': True,
            'order': [3, 7, 8, 9],
            'values': [
                {'id': 1, 'name': 'Not applicable', 'deleted': True},
                {'id': 2, 'name': 'Very boring', 'deleted': True},
                {'id': 4, 'name': 'Neither entertaining nor boring', 'deleted': True},
                {'id': 5, 'name': 'Entertaining', 'deleted': True},
                {'id': 6, 'name': 'Very entertaining', 'deleted': True},
                {'id': 3, 'name': 'Boring'},
                {'id': 7, 'name': 'Engaging'},
                {'id': 8, 'name': 'Exciting'},
                {'id': 9, 'name': 'Neutral'},
            ],
        },
        {
            'id': 3,
            'label': 'Clarity',
            'description': 'How clearly was this book written and presented?',
            'multi_choice': True,
            'order': [6, 7, 8, 9, 10, 11, 12, 13],
            'values': [
                {'id': 1, 'name': 'Not applicable', 'deleted': True},
                {'id': 2, 'name': 'Very unclearly', 'deleted': True},
                {'id': 3, 'name': 'Unclearly', 'deleted': True},
                {'id': 4, 'name': 'Clearly', 'deleted': True},
                {'id': 5, 'name': 'Very clearly', 'deleted': True},
                {'id': 6, 'name': 'Succinct'},
                {'id': 7, 'name': 'Dense'},
                {'id': 8, 'name': 'Incomprehensible'},
                {'id': 9, 'name': 'Confusing'},
                {'id': 10, 'name': 'Clearly written'},
                {'id': 11, 'name': 'Effective explanations'},
                {'id': 12, 'name': 'Well organized'},
                {'id': 13, 'name': 'Disorganized'},
            ],
        },
        {
            'id': 4,
            'label': 'Jargon',
            'description': 'How technical is the content?',
            'multi_choice': False,
            'order': [1, 2, 3, 4, 5],
            'values': [
                {'id': 1, 'name': 'Not applicable'},
                {'id': 2, 'name': 'Not technical'},
                {'id': 3, 'name': 'Somewhat technical'},
                {'id': 4, 'name': 'Technical'},
                {'id': 5, 'name': 'Very technical'},
            ],
            'deleted': True,
        },
        {
            'id': 5,
            'label': 'Originality',
            'description': 'How original is this book?',
            'multi_choice': False,
            'order': [1, 2, 3, 4, 5],
            'values': [
                {'id': 1, 'name': 'Not applicable'},
                {'id': 2, 'name': 'Very unoriginal'},
                {'id': 3, 'name': 'Somewhat unoriginal'},
                {'id': 4, 'name': 'Somewhat original'},
                {'id': 5, 'name': 'Very original'},
            ],
            'deleted': True,
        },
        {
            'id': 6,
            'label': 'Difficulty',
            'description': 'How would you rate the difficulty of '
            'this book for a general audience?',
            'multi_choice': True,
            'order': [6, 7, 8, 9, 10, 11, 12],
            'values': [
                {'id': 1, 'name': 'Not applicable', 'deleted': True},
                {'id': 2, 'name': 'Requires domain expertise', 'deleted': True},
                {'id': 3, 'name': 'A lot of prior knowledge needed', 'deleted': True},
                {'id': 4, 'name': 'Some prior knowledge needed', 'deleted': True},
                {'id': 5, 'name': 'No prior knowledge needed', 'deleted': True},
                {'id': 6, 'name': 'Beginner'},
                {'id': 7, 'name': 'Intermediate'},
                {'id': 8, 'name': 'Advanced'},
                {'id': 9, 'name': 'Expert'},
                {'id': 10, 'name': 'University'},
                {'id': 11, 'name': 'Layman'},
                {'id': 12, 'name': 'Juvenile'},
            ],
        },
        {
            'id': 7,
            'label': 'Usefulness',
            'description': 'How useful is the content of this book?',
            'multi_choice': False,
            'order': [1, 2, 3, 4, 5],
            'values': [
                {'id': 1, 'name': 'Not applicable'},
                {'id': 2, 'name': 'Not useful'},
                {'id': 3, 'name': 'Somewhat useful'},
                {'id': 4, 'name': 'Useful'},
                {'id': 5, 'name': 'Very useful'},
            ],
            'deleted': True,
        },
        {
            'id': 8,
            'label': 'Breadth',
            'description': "How would you describe the breadth and depth of this book?",
            'multi_choice': True,
            'order': [7, 8, 9, 10, 11, 12, 13],
            'values': [
                {'id': 1, 'name': 'Not applicable', 'deleted': True},
                {'id': 2, 'name': 'Much more deep', 'deleted': True},
                {'id': 3, 'name': 'Somewhat more deep', 'deleted': True},
                {'id': 4, 'name': 'Equally broad and deep', 'deleted': True},
                {'id': 5, 'name': 'Somewhat more broad', 'deleted': True},
                {'id': 6, 'name': 'Much more broad', 'deleted': True},
                {'id': 7, 'name': 'Comprehensive'},
                {'id': 8, 'name': 'Not comprehensive'},
                {'id': 9, 'name': 'Focused'},
                {'id': 10, 'name': 'Interdisciplinary'},
                {'id': 11, 'name': 'Extraneous'},
                {'id': 12, 'name': 'Shallow'},
                {'id': 13, 'name': 'Introductory'},
            ],
        },
        {
            'id': 9,
            'label': 'Objectivity',
            'description': 'Are there causes to question the accuracy of this book?',
            'multi_choice': True,
            'order': [1, 2, 3, 4, 5, 6, 7, 8],
            'values': [
                {'id': 1, 'name': 'Not applicable'},
                {'id': 2, 'name': 'No, it seems accurate'},
                {'id': 3, 'name': 'Yes, it needs citations'},
                {'id': 4, 'name': 'Yes, it is inflammatory'},
                {'id': 5, 'name': 'Yes, it has typos'},
                {'id': 6, 'name': 'Yes, it is inaccurate'},
                {'id': 7, 'name': 'Yes, it is misleading'},
                {'id': 8, 'name': 'Yes, it is biased'},
            ],
            'deleted': True,
        },
        {
            'id': 10,
            'label': 'Genres',
            'description': 'What are the genres of this book?',
            'multi_choice': True,
            'order': [
                1,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                20,
                21,
                22,
                23,
                24,
                25,
                26,
                27,
                28,
                29,
                30,
                31,
                32,
                33,
            ],
            'values': [
                {'id': 1, 'name': 'Sci-fi'},
                {'id': 2, 'name': 'Philosophy', 'deleted': True},
                {'id': 3, 'name': 'Satire'},
                {'id': 4, 'name': 'Poetry'},
                {'id': 5, 'name': 'Memoir'},
                {'id': 6, 'name': 'Paranormal'},
                {'id': 7, 'name': 'Mystery'},
                {'id': 8, 'name': 'Humor'},
                {'id': 9, 'name': 'Horror'},
                {'id': 10, 'name': 'Fantasy'},
                {'id': 11, 'name': 'Drama'},
                {'id': 12, 'name': 'Crime'},
                {'id': 13, 'name': 'Graphical'},
                {'id': 14, 'name': 'Classic'},
                {'id': 15, 'name': 'Anthology'},
                {'id': 16, 'name': 'Action'},
                {'id': 17, 'name': 'Romance'},
                {'id': 18, 'name': 'How-to'},
                {'id': 19, 'name': 'Encyclopedia'},
                {'id': 20, 'name': 'Dictionary'},
                {'id': 21, 'name': 'Technical'},
                {'id': 22, 'name': 'Reference'},
                {'id': 23, 'name': 'Textbook'},
                {'id': 24, 'name': 'Biographical'},
                {'id': 25, 'name': 'Fiction'},
                {'id': 26, 'name': 'Nonfiction'},
                {'id': 27, 'name': 'Biography'},
                {'id': 28, 'name': 'Based on a true story'},
                {'id': 29, 'name': 'Exploratory'},
                {'id': 30, 'name': 'Research'},
                {'id': 31, 'name': 'Philosophical'},
                {'id': 32, 'name': 'Essay'},
                {'id': 33, 'name': 'Review'},
            ],
        },
        {
            'id': 11,
            'label': 'Fictionality',
            'description': "Is this book a work of fact or fiction?",
            'multi_choice': False,
            'order': [1, 2, 3],
            'values': [
                {'id': 1, 'name': 'Nonfiction'},
                {'id': 2, 'name': 'Fiction'},
                {'id': 3, 'name': 'Biography'},
            ],
            'deleted': True,
        },
        {
            'id': 12,
            'label': 'Audience',
            'description': "What are the intended age groups for this book?",
            'multi_choice': True,
            'order': [1, 2, 3, 4, 5, 6, 7],
            'values': [
                {'id': 1, 'name': 'Experts'},
                {'id': 2, 'name': 'College'},
                {'id': 3, 'name': 'High school'},
                {'id': 4, 'name': 'Elementary'},
                {'id': 5, 'name': 'Kindergarten'},
                {'id': 6, 'name': 'Baby'},
                {'id': 7, 'name': 'General audiences'},
            ],
            'deleted': True,
        },
        {
            'id': 13,
            'label': 'Mood',
            'description': 'What are the moods of this book?',
            'multi_choice': True,
            'order': [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                20,
                21,
                22,
                23,
                24,
                25,
                26,
            ],
            'values': [
                {'id': 1, 'name': 'Scientific'},
                {'id': 2, 'name': 'Dry'},
                {'id': 3, 'name': 'Emotional'},
                {'id': 4, 'name': 'Strange'},
                {'id': 5, 'name': 'Suspenseful'},
                {'id': 6, 'name': 'Sad'},
                {'id': 7, 'name': 'Dark'},
                {'id': 8, 'name': 'Lonely'},
                {'id': 9, 'name': 'Tense'},
                {'id': 10, 'name': 'Fearful'},
                {'id': 11, 'name': 'Angry'},
                {'id': 12, 'name': 'Hopeful'},
                {'id': 13, 'name': 'Lighthearted'},
                {'id': 14, 'name': 'Calm'},
                {'id': 15, 'name': 'Informative'},
                {'id': 16, 'name': 'Ominous'},
                {'id': 17, 'name': 'Mysterious'},
                {'id': 18, 'name': 'Romantic'},
                {'id': 19, 'name': 'Whimsical'},
                {'id': 20, 'name': 'Idyllic'},
                {'id': 21, 'name': 'Melancholy'},
                {'id': 22, 'name': 'Humorous'},
                {'id': 23, 'name': 'Gloomy'},
                {'id': 24, 'name': 'Reflective'},
                {'id': 25, 'name': 'Inspiring'},
                {'id': 26, 'name': 'Cheerful'},
            ],
        },
        {
            'id': 14,
            'label': 'Impressions',
            'description': 'How did you feel about this book and do you recommend it?',
            'multi_choice': True,
            'order': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
            'values': [
                {'id': 1, 'name': 'Recommend'},
                {'id': 2, 'name': 'Highly recommend'},
                {'id': 3, 'name': "Don't recommend"},
                {'id': 4, 'name': 'Field defining'},
                {'id': 5, 'name': 'Actionable'},
                {'id': 6, 'name': 'Forgettable'},
                {'id': 7, 'name': 'Quotable'},
                {'id': 8, 'name': 'Citable'},
                {'id': 9, 'name': 'Original'},
                {'id': 10, 'name': 'Unremarkable'},
                {'id': 11, 'name': 'Life changing'},
                {'id': 12, 'name': 'Best in class'},
                {'id': 13, 'name': 'Overhyped'},
                {'id': 14, 'name': 'Underrated'},
            ],
        },
        {
            'id': 15,
            'label': 'Type',
            'description': 'How would you classify this work?',
            'multi_choice': True,
            'order': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            'values': [
                {'id': 1, 'name': 'Fiction'},
                {'id': 2, 'name': 'Nonfiction'},
                {'id': 3, 'name': 'Biography'},
                {'id': 4, 'name': 'Based on a true story'},
                {'id': 5, 'name': 'Textbook'},
                {'id': 6, 'name': 'Reference'},
                {'id': 7, 'name': 'Exploratory'},
                {'id': 8, 'name': 'Research'},
                {'id': 9, 'name': 'Philosophical'},
                {'id': 10, 'name': 'Essay'},
                {'id': 11, 'name': 'Review'},
                {'id': 12, 'name': 'Classic'},
            ],
            'deleted': True,
        },
        {
            'id': 16,
            'label': 'Length',
            'description': 'How would you rate or describe the length of this book?',
            'multi_choice': True,
            'order': [1, 2, 3],
            'values': [
                {'id': 1, 'name': 'Short'},
                {'id': 2, 'name': 'Medium'},
                {'id': 3, 'name': 'Long'},
            ],
        },
        {
            'id': 17,
            'label': 'Credibility',
            'description': 'How factually accurate and reliable '
            'is the content of this book?',
            'multi_choice': True,
            'order': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
            'values': [
                {'id': 1, 'name': 'Accurate'},
                {'id': 2, 'name': 'Inaccurate'},
                {'id': 3, 'name': 'Outdated'},
                {'id': 4, 'name': 'Evergreen'},
                {'id': 5, 'name': 'Biased'},
                {'id': 6, 'name': 'Objective'},
                {'id': 7, 'name': 'Subjective'},
                {'id': 8, 'name': 'Rigorous'},
                {'id': 9, 'name': 'Misleading'},
                {'id': 10, 'name': 'Controversial'},
                {'id': 11, 'name': 'Trendy'},
            ],
        },
        {
            'id': 18,
            'label': 'Features',
            'description': 'What text features does this book utilize?'
            'does this book make use of?',
            'multi_choice': True,
            'order': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
            'values': [
                {'id': 1, 'name': 'Tables, diagrams, and figures'},
                {'id': 2, 'name': 'Problem sets'},
                {'id': 3, 'name': 'Proofs'},
                {'id': 4, 'name': 'Interviews'},
                {'id': 5, 'name': 'Table of contents'},
                {'id': 6, 'name': 'Illustrations'},
                {'id': 7, 'name': 'Index'},
                {'id': 8, 'name': 'Glossary'},
                {'id': 9, 'name': 'Chapters'},
                {'id': 10, 'name': 'Appendix'},
                {'id': 11, 'name': 'Bibliography'},
            ],
        },
        {
            'id': 19,
            'label': 'Content Warnings',
            'description': 'Does this book contain objectionable content?',
            'multi_choice': True,
            'order': [1, 2, 3, 4, 5, 6],
            'values': [
                {'id': 1, 'name': 'Adult themes'},
                {'id': 2, 'name': 'Trigger warnings'},
                {'id': 3, 'name': 'Offensive language'},
                {'id': 4, 'name': 'Graphic imagery'},
                {'id': 5, 'name': 'Insensitivity'},
                {'id': 6, 'name': 'Racism'},
                {'id': 7, 'name': 'Sexual themes'},
                {'id': 8, 'name': 'Drugs'},
            ],
        },
        {
            'id': 20,
            'label': 'Style',
            'description': 'What type of verbiage, nomenclature, '
            'or symbols are employed in this book?',
            'multi_choice': True,
            'order': [1, 2, 3, 4, 5],
            'values': [
                {'id': 1, 'name': 'Technical'},
                {'id': 2, 'name': 'Jargony'},
                {'id': 3, 'name': 'Neologisms'},
                {'id': 4, 'name': 'Slang'},
                {'id': 5, 'name': 'Olde'},
            ],
        },
        {
            'id': 21,
            'label': 'Purpose',
            'description': 'Why should someone read this book?',
            'multi_choice': True,
            'order': [1, 2, 3, 4, 5, 6, 7, 8, 9],
            'values': [
                {'id': 1, 'name': 'Entertainment'},
                {'id': 2, 'name': 'Broaden perspective'},
                {'id': 3, 'name': 'How-to'},
                {'id': 4, 'name': 'Learn about'},
                {'id': 5, 'name': 'Self-help'},
                {'id': 6, 'name': 'Hope'},
                {'id': 7, 'name': 'Inspiration'},
                {'id': 8, 'name': 'Fact checking'},
                {'id': 9, 'name': 'Problem solving'},
            ],
        },
    ]
}

class ObservationCount:
    def __init__(self, type_id, value_id, count):
        self.type_id = type_id
        self.value_id = value_id
        self.count = count
        self.observation = Observation(type_id, value_id)

    def csv_values(self):
        return [self.observation.type, self.type_id, self.observation.description, self.observation.value, self.value_id, self.observation.deleted, self.count]


class Observation:
    def __init__(self, type_id, value_id):
        self.type, self.description, self.value, self.deleted = self._map_to_strings(type_id, value_id)

    def _map_to_strings(self, type_id, value_id):
        observation = next((o for o in OBSERVATIONS['observations'] if o['id'] == type_id), None)
        value = next((v for v in observation['values'] if v['id'] == value_id), None)
        return (observation['label'], observation['description'], value['name'], value.get('deleted', False))


def intake(infile):
    counts = []
    with open(infile, 'r') as f:
        for line in f:
            values = line.strip().split()
            counts.append(ObservationCount(int(values[0]), int(values[1]), int(values[2])))
    return counts


def write_to_csv(data, outfile):
    with open(outfile, 'w') as f:
        writer = csv.writer(f, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
        writer.writerow(['Type', 'Type ID', 'Type Description', 'Value', 'Value ID', 'Is Deleted', 'Total'])
        for d in data:
            writer.writerow(d.csv_values())

